#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v4
# autospec commit: da8b975
#
Name     : numactl
Version  : 2.0.18
Release  : 29
URL      : https://github.com/numactl/numactl/archive/v2.0.18/numactl-2.0.18.tar.gz
Source0  : https://github.com/numactl/numactl/archive/v2.0.18/numactl-2.0.18.tar.gz
Summary  : libnuma libraries
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: numactl-bin = %{version}-%{release}
Requires: numactl-lib = %{version}-%{release}
Requires: numactl-license = %{version}-%{release}
Requires: numactl-man = %{version}-%{release}
BuildRequires : util-linux
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Simple NUMA policy support. It consists of a numactl program to run
other programs with a specific NUMA policy.

%package bin
Summary: bin components for the numactl package.
Group: Binaries
Requires: numactl-license = %{version}-%{release}

%description bin
bin components for the numactl package.


%package dev
Summary: dev components for the numactl package.
Group: Development
Requires: numactl-lib = %{version}-%{release}
Requires: numactl-bin = %{version}-%{release}
Provides: numactl-devel = %{version}-%{release}
Requires: numactl = %{version}-%{release}

%description dev
dev components for the numactl package.


%package lib
Summary: lib components for the numactl package.
Group: Libraries
Requires: numactl-license = %{version}-%{release}

%description lib
lib components for the numactl package.


%package license
Summary: license components for the numactl package.
Group: Default

%description license
license components for the numactl package.


%package man
Summary: man components for the numactl package.
Group: Default

%description man
man components for the numactl package.


%prep
%setup -q -n numactl-2.0.18
cd %{_builddir}/numactl-2.0.18
pushd ..
cp -a numactl-2.0.18 buildavx2
popd
pushd ..
cp -a numactl-2.0.18 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707417288
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
pushd ../buildapx/
GOAMD64=v3
CC=gcc-14
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --host=x86_64-clr-linux-gnu --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707417288
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numactl
cp %{_builddir}/numactl-%{version}/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/numactl/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/numactl-%{version}/LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/numactl/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v3
pushd ../buildapx/
%make_install_va
popd
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/share/man/man2/move_pages.2
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/memhog
/V3/usr/bin/migratepages
/V3/usr/bin/migspeed
/V3/usr/bin/numactl
/V3/usr/bin/numademo
/V3/usr/bin/numastat
/usr/bin/memhog
/usr/bin/migratepages
/usr/bin/migspeed
/usr/bin/numactl
/usr/bin/numademo
/usr/bin/numastat

%files dev
%defattr(-,root,root,-)
/usr/include/numa.h
/usr/include/numacompat1.h
/usr/include/numaif.h
/usr/lib64/libnuma.so
/usr/lib64/pkgconfig/numa.pc
/usr/share/man/man3/numa.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libnuma.so.1.0.0
/usr/lib64/libnuma.so.1
/usr/lib64/libnuma.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numactl/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/numactl/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/memhog.8
/usr/share/man/man8/migratepages.8
/usr/share/man/man8/migspeed.8
/usr/share/man/man8/numactl.8
/usr/share/man/man8/numastat.8
